OpenShift:
  enabled: false
  createSCC: false

postgresql:
  enabled: true

jwtSecret: dZ0EB0KxnF++nr5+4vfTCaun/eWbv6gOoXodiAMqcFo=

image:
  pullSecrets:
    - name: pullsecret
  repository: "sonarsource/sonarqube"
  tag: "10.7.0-community"
