apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  namespace: clustersecret
  name: pullsecret
matchNamespace:
  - '*'
avoidNamespaces:
  - default
  - kube-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: DOCKER_CONFIG_JSON
