sonarqube_dce_chart_static_compatibility_test_task:
  <<: *CHART_STATIC_COMPATIBILITY_TEST_TEMPLATE
  skip: "!changesInclude('charts/sonarqube-dce/**/*', 'tests/unity-compatibility-test/sonarqube-dce/*', '.cirrus/*.sh', '.cirrus/tasks{_sonarqube_dce,_templates,}.yml', '.cirrus/tasks.star', '.cirrus.star')"
  script:
    - ./.cirrus/build_chart_dependencies.sh charts/sonarqube-dce
    - ./.cirrus/unit_helm_compatibility_test.sh sonarqube-dce

chart_testing_on_openshift_sonarqube_dce_task:
  <<: *CHART_TESTING_ON_OPENSHIFT_TEMPLATE
  skip: "!changesInclude('charts/sonarqube-dce/**/*', 'tests/unity-compatibility-test/sonarqube-dce/*', '.cirrus/*.sh', '.cirrus/tasks{_sonarqube_dce,_templates,}.yml', '.cirrus/tasks.star', '.cirrus.star')"
  env:
    - VERIFYING_CHART: sonarqube-dce

sonarqube_dce_chart_packaging_task:
  <<: *CHART_PACKAGING_TASK_TEMPLATE
  skip: "!changesInclude('charts/sonarqube-dce/**/*', 'tests/unity-compatibility-test/sonarqube-dce/*', '.cirrus/*.sh', '.cirrus/tasks{_sonarqube_dce,_templates,}.yml', '.cirrus/tasks.star', '.cirrus.star')"
  script:
    - source cirrus-env BUILD
    - ./.cirrus/package.sh sonarqube-dce
    - ./.cirrus/sign_chart.sh sonarqube-dce
  depends_on:
    - chart_testing_on_kind
    - chart_testing_on_openshift_sonarqube_dce

sonarqube_dce_push_to_repox_task:
  <<: *PUSH_TO_REPOX_TASK_TEMPLATE
  skip: "!changesInclude('charts/sonarqube-dce/**/*', 'tests/unity-compatibility-test/sonarqube-dce/*', '.cirrus/*.sh', '.cirrus/tasks{_sonarqube_dce,_templates,}.yml', '.cirrus/tasks.star', '.cirrus.star')"
  script:
    - source cirrus-env ""
    - ./.cirrus/upload_chart.sh sonarqube-dce
  depends_on:
    - sonarqube_dce_chart_packaging

sonarqube_dce_trigger_release_task:
  <<: *TRIGGER_RELEASE_TASK_TEMPLATE
  skip: "!changesInclude('charts/sonarqube-dce/**/*', 'tests/unity-compatibility-test/sonarqube-dce/*', '.cirrus/*.sh', '.cirrus/tasks{_sonarqube_dce,_templates,}.yml', '.cirrus/tasks.star', '.cirrus.star')"
  depends_on:
    - sonarqube_dce_chart_packaging
    - sonarqube_dce_push_to_repox
