SKIP_IF_NOT_SONARQUBE_DCE: &SKIP_IF_NOT_SONARQUBE_DCE
  skip: "!changesInclude('charts/sonarqube-dce/*', 'charts/sonarqube-dce/**/*', 'tests/unity-compatibility-test/sonarqube-dce/*', '.cirrus/*.sh', '.cirrus/tasks{_sonarqube_dce,_templates,}.yml', '.cirrus/tasks.star', '.cirrus.star')"

sonarqube_dce_chart_static_compatibility_test_task:
  <<: *CHART_STATIC_COMPATIBILITY_TEST_TEMPLATE
  <<: *SKIP_IF_NOT_SONARQUBE_DCE
  script:
    - ./.cirrus/build_chart_dependencies.sh charts/sonarqube-dce
    - ./.cirrus/unit_helm_compatibility_test.sh sonarqube-dce

chart_testing_on_openshift_sonarqube_dce_task:
  <<: *CHART_TESTING_ON_OPENSHIFT_TEMPLATE
  <<: *SKIP_IF_NOT_SONARQUBE_DCE
  env:
    - VERIFYING_CHART: sonarqube-dce
  depends_on:
    - sonarqube_dce_chart_static_compatibility_test

chart_testing_on_kind_sonarqube_dce_task:
  <<: *CHART_TESTING_ON_KIND_TEMPLATE
  <<: *SKIP_IF_NOT_SONARQUBE_DCE
  script:
    - ct lint --config ct-sonarqube-dce-test.yaml --all
    - ct install --namespace test --config ct-sonarqube-dce-test.yaml --all --debug
  depends_on:
    - sonarqube_dce_chart_static_compatibility_test

sonarqube_dce_chart_packaging_task:
  <<: *CHART_PACKAGING_TASK_TEMPLATE
  <<: *SKIP_IF_NOT_SONARQUBE_DCE
  environment_cache:
    folder: ${CIRRUS_WORKING_DIR}/*.tgz*
    fingerprint_script: echo "${CIRRUS_BUILD_ID}-sonarqube-dce"
  script:
    - source cirrus-env BUILD
    - ./.cirrus/package.sh sonarqube-dce
    - ./.cirrus/sign_chart.sh sonarqube-dce
  depends_on:
    - chart_testing_on_kind_sonarqube_dce
    - chart_testing_on_openshift_sonarqube_dce

sonarqube_dce_push_to_repox_task:
  <<: *PUSH_TO_REPOX_TASK_TEMPLATE
  <<: *SKIP_IF_NOT_SONARQUBE_DCE
  environment_cache:
    folder: ${CIRRUS_WORKING_DIR}/*.tgz*
    fingerprint_script: echo "${CIRRUS_BUILD_ID}-sonarqube-dce"
  script:
    - source cirrus-env ""
    - ./.cirrus/upload_chart.sh sonarqube-dce
  depends_on:
    - sonarqube_dce_chart_packaging
