env:
### Shared variables
  NIGHTLY_CRON: 'nightly-cron'
  DOCKER_USERNAME: VAULT[development/kv/data/docker/sonardockerrw data.username]
  DOCKER_PASSWORD: VAULT[development/kv/data/docker/sonardockerrw data.access_token_rwd]
  KUBE_VERSION: 1.29.0
  DOCKER_GCLOUD_SA_KEY: VAULT[development/team/sonarqube/kv/data/gcp-marketplace-registry-staging data.key]
  GCLOUD_REGISTRY: gcr.io/sonarqube-marketplace-provider # This is the staging registry
  GCLOUD_PRODUCT_NAME: sonarqube-dce-staging # This is the staging product name
  GCLOUD_TAG: 10.5.0

except_nightly_cron: &EXCEPT_ON_NIGHTLY_CRON
  only_if: $CIRRUS_CRON != $NIGHTLY_CRON

only_on_non_release_draft_template: &ONLY_ON_NON_RELEASE_DRAFT_TEMPLATE
  only_if: $CIRRUS_PRERELEASE != "true"

docker_build_container_template: &CONTAINER_TEMPLATE
  dockerfile: .cirrus/Dockerfile
  docker_arguments:
      CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
  cluster_name: ${CIRRUS_CLUSTER_NAME}
  builder_role: cirrus-builder
  builder_image: docker-builder-v*
  builder_instance_type: t2.small
  builder_subnet_id: ${CIRRUS_AWS_SUBNET}
  region: eu-central-1
  namespace: default
  cpu: 1
  memory: 1Gb

container_template: &STD_CONTAINER_TEMPLATE
  image: ${CIRRUS_AWS_ACCOUNT}.dkr.ecr.eu-central-1.amazonaws.com/base:j11-latest
  cluster_name: ${CIRRUS_CLUSTER_NAME}
  region: eu-central-1
  namespace: default
  cpu: 1
  memory: 1Gb

vm_instance_template: &VM_TEMPLATE
  image: docker-builder-v*
  type: t2.small
  region: eu-central-1
  subnet_id: ${CIRRUS_AWS_SUBNET}

clone_script_template: &CLONE_SCRIPT_TEMPLATE
  clone_script: |
    if [ -z "$CIRRUS_PR" ]; then
      git clone --recursive --branch=$CIRRUS_BRANCH https://github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    else
      git clone --recursive https://github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
      git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    fi

build_gcp_staging_app_task: &BUILD_GCP_STAGING_APP_TASK
  only_if: $TRIGGER == "PUSH_STAGING_DEPLOYER" || $BRANCH == "master"
  ec2_instance:
    <<: *VM_TEMPLATE
  login_to_gcr_script:
    - export DOCKER_GCLOUD_PASSWORD=$(echo ${DOCKER_GCLOUD_SA_KEY} | base64 -d)
    - docker login -u _json_key -p "$DOCKER_GCLOUD_PASSWORD" https://${GCLOUD_REGISTRY}
  install_helm_script:
    - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    - chmod 700 get_helm.sh
    - ./get_helm.sh
  helm_dependency_build_script:
    - cd charts/sonarqube-dce
    - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm repo add bitnami-pre2022 https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    - helm dependency build
  tag_and_promote_script:
    - export CURRENT_MINOR_VERSION=$(echo ${GCLOUD_TAG} | cut -d '.' -f 1,2)
    - docker build -f google-cloud-marketplace-k8s-app/Dockerfile --build-arg REGISTRY=${GCLOUD_REGISTRY} --build-arg TAG=${GCLOUD_TAG} --tag ${GCLOUD_REGISTRY}/${GCLOUD_PRODUCT_NAME}/deployer:${CURRENT_MINOR_VERSION} .
    - docker tag ${GCLOUD_REGISTRY}/${GCLOUD_PRODUCT_NAME}/deployer:${CURRENT_MINOR_VERSION} ${GCLOUD_REGISTRY}/${GCLOUD_PRODUCT_NAME}/deployer:${GCLOUD_TAG}
    - docker push ${GCLOUD_REGISTRY}/${GCLOUD_PRODUCT_NAME}/deployer:${GCLOUD_TAG}
    - docker push ${GCLOUD_REGISTRY}/${GCLOUD_PRODUCT_NAME}/deployer:${CURRENT_MINOR_VERSION}

verify_gcp_staging_app_task: &VERIFY_GCP_STAGING_APP_TASK
  only_if: $TRIGGER == "PUSH_STAGING_DEPLOYER" || $BRANCH == "master"
  env:
    BASE_FOLDER: "/root/.gcp/cache"
    PATH: "${BASE_FOLDER}/bin:${BASE_FOLDER}/google-cloud-sdk/bin:${PATH}"
    KUBE_CONFIG: "/tmp/kubeconfig"
    KUBECONFIG: "${KUBE_CONFIG}"
    HOME: "/tmp"
  gcp_cache:
    folder: ${BASE_FOLDER}
    fingerprint_script: grep "gcloud" .tool-versions | awk '{print $NF}'
    populate_script: 
      - ./.cirrus/setup.sh
  ec2_instance:
    <<: *VM_TEMPLATE
  login_script:
    - echo ${DOCKER_GCLOUD_SA_KEY} | base64 -d > /tmp/key.json
    - gcloud auth activate-service-account cirrusciservice@sonarqube-marketplace-provider.iam.gserviceaccount.com --key-file /tmp/key.json --project=sonarqube-marketplace-provider
    - gcloud container clusters get-credentials sonarqube-marketplace-staging-standard --zone=europe-west1-b --project=sonarqube-marketplace-provider
  verify_script:
    - kubectl get pods
    - mpdev verify --deployer=$GCLOUD_REGISTRY/$GCLOUD_PRODUCT_NAME/deployer:$GCLOUD_TAG --wait_timeout=1200 --parameters='{"name":"${GCLOUD_PRODUCT_NAME}-cirrus-test", "namespace":"test-cirrus","ApplicationNodes.jwtSecret":"dZ0EB0KxnF++nr5+4vfTCaun/eWbv6gOoXodiAMqcFo=", "postgresql.enabled":true, "jdbcOverwrite.enable":false }'
  depends_on:
    - build_gcp_staging_app

chart_static_compatibility_test_task:
  <<: *ONLY_ON_NON_RELEASE_DRAFT_TEMPLATE
  timeout_in: 30m
  eks_container:
    <<: *CONTAINER_TEMPLATE
    cpu: 1
    memory: 1Gb
  <<: *CLONE_SCRIPT_TEMPLATE
  script:
    - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm repo add bitnami-pre2022 https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    - cd ${CIRRUS_WORKING_DIR}/charts/sonarqube
    - helm dependency build
    - ../../.cirrus/unit_helm_compatibility_test.sh
    - cd ${CIRRUS_WORKING_DIR}/charts/sonarqube-dce
    - helm dependency build
    - ../../.cirrus/unit_helm_compatibility_test.sh    

chart_testing_task:
  <<: *ONLY_ON_NON_RELEASE_DRAFT_TEMPLATE
  timeout_in: 30m
  eks_container:
    <<: *CONTAINER_TEMPLATE
    cpu: 2
    memory: 4Gb
    additional_containers:
      - name: dockerdaemon
        privileged: true
        cpu: 4
        memory: 16Gb
        image: public.ecr.aws/docker/library/docker:dind
        port: 2375
        env:
          DOCKER_DRIVER: overlay2
          DOCKER_TLS_CERTDIR: ""
  <<: *CLONE_SCRIPT_TEMPLATE
  start_kind_script:
    - export DOCKER_HOST=tcp://localhost:2375
    - ./.cirrus/wait_for_kind.sh
  script:
    - kubectl create namespace test
    - kubectl create secret docker-registry pullsecret --namespace test --docker-username=${DOCKER_USERNAME} --docker-password=${DOCKER_PASSWORD}
    - ct lint --config test.yaml --all
    - ct install --namespace test --config test.yaml --all
  artifacthub_lint_script:
    - ah lint
  depends_on:
    - chart_static_compatibility_test

chart_packaging_task:
  <<: *ONLY_ON_NON_RELEASE_DRAFT_TEMPLATE
  timeout_in: 15m
  eks_container:
    <<: *CONTAINER_TEMPLATE
    cpu: 2
    memory: 1Gb
  <<: *CLONE_SCRIPT_TEMPLATE
  environment_cache:
    folder: ${CIRRUS_WORKING_DIR}/*.tgz*
    fingerprint_script: echo $CIRRUS_BUILD_ID
  env:
    GITHUB_TOKEN: VAULT[development/github/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-releases token]
    SONARSOURCE_SIGN_KEY: VAULT[development/kv/data/sign data.key]
    SONARSOURCE_SIGN_KEY_ID: VAULT[development/kv/data/sign data.key_id]
    SONARSOURCE_SIGN_KEY_PASSPHRASE: VAULT[development/kv/data/sign data.passphrase]
  key_file:
    path: /tmp/key
    variable_name: SONARSOURCE_SIGN_KEY
  script:
    - source cirrus-env BUILD
    - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm repo add bitnami-pre2022 https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    - helm repo update
    - ./.cirrus/package.sh
    - ./.cirrus/sign_chart.sh
  depends_on:
    - chart_testing

push_to_repox_task:
  <<: *ONLY_ON_NON_RELEASE_DRAFT_TEMPLATE
  <<: *EXCEPT_ON_NIGHTLY_CRON
  timeout_in: 15m
  eks_container:
    <<: *STD_CONTAINER_TEMPLATE
    cpu: 1
    memory: 1Gb
  <<: *CLONE_SCRIPT_TEMPLATE
  environment_cache:
    folder: ${CIRRUS_WORKING_DIR}/*.tgz*
    fingerprint_script: echo $CIRRUS_BUILD_ID
  env:
    ARTIFACTORY_URL: VAULT[development/kv/data/repox data.url]
    ARTIFACTORY_ACCESS_TOKEN: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer access_token]
  script:
    - source cirrus-env ""
    - ./.cirrus/upload_chart.sh
  depends_on:
    - chart_testing
    - chart_packaging

trigger_release_task:
  timeout_in: 15m
  eks_container:
    <<: *STD_CONTAINER_TEMPLATE
    cpu: 1
    memory: 1Gb
  only_if: $CIRRUS_PRERELEASE != "true" && $CIRRUS_RELEASE != ""
  <<: *CLONE_SCRIPT_TEMPLATE
  stateful: 'true'
  environment_cache:
    folder: ${CIRRUS_WORKING_DIR}/*.tgz*
    fingerprint_script: echo $CIRRUS_BUILD_ID
  env:
    GITHUB_TOKEN: VAULT[development/github/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-releases token]
    SLACK_TOKEN: VAULT[development/kv/data/slack data.token]
  gh_action_script: |
    source cirrus-env RELEASE
    CHARTS=$(find $CIRRUS_WORKING_DIR -maxdepth 1 -name "*.tgz*" -type f -exec basename "{}" ";")
    [[ "x$CHARTS" == "x" ]] && exit 0
    gh workflow run release.yml -f version=$CIRRUS_TAG -f buildNumber=$BUILD_NUMBER
  depends_on:
    - chart_packaging
    - push_to_repox
  on_failure:
    slack_notification_script:
      - ./.cirrus/slack-notification.sh

build_gcp_prod_app_task:
  <<: *BUILD_GCP_STAGING_APP_TASK
  only_if: $TRIGGER == "PUSH_PROD_DEPLOYER"
  env:
    GCLOUD_TAG: 10.4.1
    GCLOUD_PRODUCT_NAME: sonarqube-dce-staging

verify_gcp_prod_app_task:
  <<: *VERIFY_GCP_STAGING_APP_TASK
  only_if: $TRIGGER == "PUSH_PROD_DEPLOYER"
  env:
    GCLOUD_TAG: 10.4.1
    GCLOUD_PRODUCT_NAME: sonarqube-dce-staging
  depends_on:
    - build_gcp_prod_app

release_gcp_prod_app_task:
  <<: *BUILD_GCP_STAGING_APP_TASK
  only_if: $TRIGGER == "PUSH_PROD_DEPLOYER"
  env:
    GCLOUD_REGISTRY: gcr.io/sonarsource-public
    GCLOUD_PRODUCT_NAME: official-sonarqube-data-center-edition
    GCLOUD_TAG: 10.4.1
  depends_on:
    - verify_gcp_prod_app