chart_fixture_test_task:
  <<: *ONLY_ON_NON_RELEASE_DRAFT_TEMPLATE
  skip: "!changesInclude('charts/**/*', '.cirrus/*') && $CIRRUS_CRON != $NIGHTLY_CRON"
  timeout_in: 30m
  eks_container:
    <<: *CONTAINER_TEMPLATE
    cpu: 1
    memory: 2Gb
  <<: *CLONE_SCRIPT_TEMPLATE
  script:
    - ./.cirrus/build_chart_dependencies.sh charts/sonarqube
    - ./.cirrus/build_chart_dependencies.sh charts/sonarqube-dce
    - ./.cirrus/generate_helm_fixtures.sh
    - git diff --exit-code

chart_schema_test_task:
  skip: "!changesInclude('charts/**/*', '.cirrus/schema_test.sh', 'tests/unit-test/*', 'tests/unit-test/**/*') && $CIRRUS_CRON != $NIGHTLY_CRON"
  eks_container:
    <<: *CONTAINER_TEMPLATE
    cpu: 1
    memory: 2Gb
  <<: *CLONE_SCRIPT_TEMPLATE
  script:
    - ./.cirrus/build_chart_dependencies.sh charts/sonarqube
    - ./.cirrus/build_chart_dependencies.sh charts/sonarqube-dce
    - ./.cirrus/schema_test.sh
