dependencies:
- name: postgresql
  version: 8.6.4
  repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
  condition: postgresql.enabled
- name: ingress-nginx
  version: 3.29.0
  repository: https://kubernetes.github.io/ingress-nginx
  condition: nginx.enabled
