#
# Copyright (c) 2012-2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
{{- if .Values.global.tls.enabled }}
  tls:
  - hosts:
    - {{ template "keycloakHost" . }}
    secretName: {{ .Values.global.tls.secretName }}
{{- end }}
  rules:
{{- if eq .Values.global.serverStrategy "default-host" }}
  - http:
      paths:
      - path: /auth/
{{- else if eq .Values.global.serverStrategy "single-host" }}
  - host: {{ template "keycloakHost" . }}
    http:
      paths:
      - path: /auth/
{{- else }}
  - host: {{ template "keycloakHost" . }}
    http:
      paths:
      - path: /
{{- end }}
        backend:
          serviceName: keycloak
          servicePort: 5050
