#!/bin/bash

set -e

# get script dir
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# generate base values
(
    cd ${SCRIPT_DIR}/../testdata/snippets
    cat << EOF > base-values.yaml
# DO NOT EDIT
# This file is generated by generate-values-snippet.sh"
EOF

    yq eval-all '. as $item ireduce ({}; . * $item )' \
        values-custom-resource.yaml \
        values-custom-root-password.yaml \
        values-pg.yaml \
        values-image.yaml \
        >> base-values.yaml
)