apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sonarqube.fullname" . }}-install-plugins
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  install_plugins.sh: |-
    {{- if .Values.plugins.httpProxy }}
    export http_proxy={{ .Values.plugins.httpProxy }}
    {{- end }}
    {{- if .Values.plugins.httpsProxy }}
    export https_proxy={{ .Values.plugins.httpsProxy }}
    {{- end }}
    {{- if .Values.plugins.noProxy }}
    export no_proxy={{ .Values.plugins.noProxy }}
    {{- end }}
    {{- if .Values.plugins.install }}
      [ -e {{ .Values.sonarqubeFolder }}/extensions/downloads/* ] && rm {{ .Values.sonarqubeFolder }}/extensions/downloads/*
      {{ range $index, $val := .Values.plugins.install }}
      echo {{ $val | quote }} >> {{ $.Values.sonarqubeFolder }}/extensions/downloads/list{{ end }}
      cat {{ .Values.sonarqubeFolder }}/extensions/downloads/list | xargs -n 1 -P 8 wget --directory-prefix {{ .Values.sonarqubeFolder }}/extensions/downloads --no-verbose{{ if .Values.plugins.noCheckCertificate }} --no-check-certificate{{ end }}
      rm {{ .Values.sonarqubeFolder }}/extensions/downloads/list
    {{- end }}
    {{- if .Values.plugins.lib }}
    {{- range $index, $val := .Values.plugins.lib }}
      cp -f {{ $.Values.sonarqubeFolder }}/extensions/downloads/{{ $val }} {{ $.Values.sonarqubeFolder }}/lib/common/{{ $val }}
    {{- end }}
    {{- end }}