x-google-marketplace:
  clusterConstraints:
    istio:
      type: UNSUPPORTED
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      SonarQube Server 2026.1.x google cloud marketpalce release test schema.
  images:
    '':
      properties:
        ApplicationNodes.image.repository:
          type: REPO_WITH_REGISTRY
        ApplicationNodes.image.tag:
          type: TAG
    sonarqube-dce-search:
      properties:
        searchNodes.image.repository:
          type: REPO_WITH_REGISTRY
        searchNodes.image.tag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  ApplicationNodes.jwtSecret:
    title: JWT Token for app authentication
    description: A HS256 key encoded with base64 (This value must be set before installing the app, see documentation for more details)
    maxLength: 44
    type: string
    default: dZ0EB0KxnF++nr5+4vfTCaun/eWbv6gOoXodiAMqcFo=
    x-google-marketplace:
      type: MASKED_FIELD
  monitoringPasscode:
    title: Monitoring Passcode
    description: A string encoded with base64 used to verify SonarQube Server's liveness. Please refer to docs.sonarsource.com for more details.
    type: string
    default: dGVzdA==
    x-google-marketplace:
      type: MASKED_FIELD
  jdbcOverwrite.jdbcUrl:
    title: JDBC URL
    description: The JDBC URL to connect to the database
    type: string
    default: 'jdbc:postgresql://myPostgres/myDatabase'
  jdbcOverwrite.jdbcUsername:
    title: JDBC Username
    description: The username to connect to the database
    type: string
    default: 'username'
  jdbcOverwrite.jdbcPassword:
    title: JDBC Password
    description: The password to connect to the database
    type: string
    default: 'password'
    x-google-marketplace:
        type: MASKED_FIELD
required:
- name
- namespace
- monitoringPasscode
- ApplicationNodes.jwtSecret
- jdbcOverwrite.jdbcUrl
- jdbcOverwrite.jdbcUsername
