x-google-marketplace:
  clusterConstraints:
    istio:
      type: UNSUPPORTED
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      A first release.
  images:
    '':
      properties:
        ApplicationNodes.image.repository:
          type: REPO_WITH_REGISTRY
        ApplicationNodes.image.tag:
          type: TAG
    sonarqube-dce-search:
      properties:
        searchNodes.image.repository:
          type: REPO_WITH_REGISTRY
        searchNodes.image.tag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  appUid:
    type: string
    x-google-marketplace:
      type: APPLICATION_UID
      applicationUid:
        generatedProperties:
          createApplicationBoolean: application.create
  ApplicationNodes.jwtSecret:
    title: JWT Token for app authentication
    description: A HS256 key encoded with base64 (This value must be set before installing the app, see documentation for more details)
    maxLength: 44
    type: string
    default: dZ0EB0KxnF++nr5+4vfTCaun/eWbv6gOoXodiAMqcFo=
    x-google-marketplace:
      type: MASKED_FIELD
  postgresql.enabled:
    title: Enable embedded PostgreSQL
    description: If true, PostgreSQL will be installed (not recommended for production use case)
    type: boolean
    default: true
  jdbcOverwrite.enable:
    title: Enable external DB configuration
    description: If true, the JDBC URL, username and password will be used to connect to the database. Make sure enable embedded PostgreSQL is set to false
    type: boolean
    default: false
  jdbcOverwrite.jdbcUrl:
    title: JDBC URL
    description: The JDBC URL to connect to the database
    type: string
    default: ''
  jdbcOverwrite.jdbcUsername:
    title: JDBC Username
    description: The username to connect to the database
    type: string
    default: ''
  jdbcOverwrite.jdbcPassword:
    title: JDBC Password
    description: The password to connect to the database
    type: string
    default: ''

required:
- name
- namespace
- ApplicationNodes.jwtSecret
