x-google-marketplace:
  clusterConstraints:
    istio:
      type: UNSUPPORTED
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      Sonarqube 10.7.x google cloud marketpalce release test schema.
  images:
    '':
      properties:
        ApplicationNodes.image.repository:
          type: REPO_WITH_REGISTRY
        ApplicationNodes.image.tag:
          type: TAG
    sonarqube-dce-search:
      properties:
        searchNodes.image.repository:
          type: REPO_WITH_REGISTRY
        searchNodes.image.tag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  ApplicationNodes.jwtSecret:
    title: JWT Token for app authentication
    description: A HS256 key encoded with base64 (This value must be set before installing the app, see documentation for more details)
    maxLength: 44
    type: string
    default: dZ0EB0KxnF++nr5+4vfTCaun/eWbv6gOoXodiAMqcFo=
    x-google-marketplace:
      type: MASKED_FIELD
  postgresql.enabled:
    title: Enable embedded PostgreSQL
    description: If true, PostgreSQL will be installed (not recommended for production use case)
    type: boolean
    default: true
  jdbcOverwrite.enabled:
    title: Connection to a database - Recommended
    description: Connect SonarQube to your PostgreSQL database. The connection parameters JDBC URL, username, and password will be used. Make sure that the Embedded database option is disabled.
    type: boolean
    default: false
required:
- name
- namespace
- ApplicationNodes.jwtSecret
