apiVersion: v2
name: sonarqube
description: SonarQube is a self-managed, automatic code review tool that systematically helps you deliver clean code. As a core element of our Sonar solution, SonarQube integrates into your existing workflow and detects issues in your code to help you perform continuous code inspections of your projects. The tool analyses 30+ different programming languages and integrates into your CI pipeline and DevOps platform to ensure that your code meets high-quality standards.
type: application
version: 2025.2.0
appVersion: 2025.2.0
keywords:
  - coverage
  - security
  - code
  - quality
home: https://www.sonarqube.org/
icon: https://raw.githubusercontent.com/SonarSource/sonarqube-static-resources/master/helm/SonarQubeServerLogo.png
sources:
  - https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube
  - https://github.com/SonarSource/docker-sonarqube
  - https://github.com/SonarSource/sonarqube
kubeVersion: ">= 1.24.0-0"
maintainers:
  - name: carminevassallo
    email: carmine.vassallo@sonarsource.com
  - name: jCOTINEAU
    email: jeremy.cotineau@sonarsource.com
  - name: davividal
    email: davi.koscianski-vidal@sonarsource.com
dependencies:
  - name: sonarqube
    version: 2025.3.0
    repository: "file://../charts/sonarqube"
