{{- if and .Values.agenticHarness.enabled (not .Values.agenticHarness.orchestrator.storage.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sonarqube.agentic.orchestrator.fullname" . }}-storage
  labels: {{- include "sonarqube.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ .Values.agenticHarness.orchestrator.storage.accessKey | b64enc | quote }}
  secret-key: {{ .Values.agenticHarness.orchestrator.storage.secretKey | b64enc | quote }}
{{- end }}
