{{- if .Values.mcp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonarqube.mcp.fullname" . }}
  labels: {{- include "sonarqube.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mcp.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "sonarqube.name" . }}-mcp
    release: {{ .Release.Name }}
{{- end }}
