{{ $accountDeprecation := fromYaml (include "accountDeprecation" . ) }}
{{ $_ := set .Values "account" $accountDeprecation }}
---
{{- if and (or .Values.jdbcOverwrite.enabled .Values.jdbcOverwrite.enable) (not .Values.jdbcOverwrite.jdbcSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sonarqube.fullname" . }}
  labels: {{- include "sonarqube.labels" . | nindent 4 }}
type: Opaque
data:
  {{ template "jdbc.secretPasswordKey" . }}: {{ template "jdbc.internalSecretPasswd" . }}
{{- end }}
---
{{- if and .Values.monitoringPasscode (not .Values.monitoringPasscodeSecretName) (not .Values.monitoringPasscodeSecretKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sonarqube.fullname" . }}-monitoring-passcode
  labels: {{- include "sonarqube.labels" . | nindent 4 }}
type: Opaque
data:
  SONAR_WEB_SYSTEMPASSCODE: {{ .Values.monitoringPasscode | b64enc | quote }}
{{- end }}
---
{{- if .Values.account }}
{{- if or .Values.account.adminPassword .Values.account.newPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sonarqube.fullname" . }}-admin-password
  labels: {{- include "sonarqube.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.account.adminPassword | default .Values.account.newPassword | quote }}
  currentPassword: {{ .Values.account.currentAdminPassword | default .Values.account.currentPassword | quote }}
{{- end }}
{{- end }}
---
{{ if eq (include "sonarqube.hasProxyConfig" .) "true" }}
{{ $pluginsHttpProxy := default .Values.httpProxy .Values.plugins.httpProxy -}}
{{ $pluginsHttpsProxy := default .Values.httpsProxy .Values.plugins.httpsProxy -}}
{{ $pluginsNoProxy := default .Values.noProxy .Values.plugins.noProxy -}}
{{ $prometheusHttpProxy := default .Values.httpProxy .Values.prometheusExporter.httpProxy -}}
{{ $prometheusHttpsProxy := default .Values.httpsProxy .Values.prometheusExporter.httpsProxy -}}
{{ $prometheusNoProxy := default .Values.noProxy .Values.prometheusExporter.noProxy -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sonarqube.fullname" . }}-http-proxies
  labels: {{- include "sonarqube.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if eq (include "sonarqube.hasPluginsProxyConfig" .) "true" }}
  {{- if $pluginsHttpProxy }}
  PLUGINS-HTTP-PROXY: {{ $pluginsHttpProxy | quote }}
  {{- end }}
  {{- if $pluginsHttpsProxy }}
  PLUGINS-HTTPS-PROXY: {{ $pluginsHttpsProxy | quote }}
  {{- end }}
  {{- if $pluginsNoProxy }}
  PLUGINS-NO-PROXY: {{ $pluginsNoProxy | quote }}
  {{- end }}
  {{- end }}
  {{- if eq (include "sonarqube.hasPrometheusExporterProxyConfig" .) "true" }}
  {{- if $prometheusHttpProxy }}
  PROMETHEUS-EXPORTER-HTTP-PROXY: {{ $prometheusHttpProxy | quote }}
  {{- end }}
  {{- if $prometheusHttpsProxy }}
  PROMETHEUS-EXPORTER-HTTPS-PROXY: {{ $prometheusHttpsProxy | quote }}
  {{- end }}
  {{- if $prometheusNoProxy }}
  PROMETHEUS-EXPORTER-NO-PROXY: {{ $prometheusNoProxy | quote }}
  {{- end }}
  {{- end }}
{{- end -}}
