apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sonarqube.fullname" . }}-init-fs
  labels: {{- include "sonarqube.labels" . | nindent 4 }}
data:
  init_fs.sh: |-
    {{- if .Values.searchNodes.persistence.enabled }}
    chown -R {{ .Values.searchNodes.persistence.uid }}:{{ .Values.searchNodes.persistence.guid }} {{ .Values.sonarqubeFolder }}
    {{- end }}
