apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sonarqube.fullname" . }}-config
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if and .Values.sonarSecretKey (not .Values.sonarProperties) }}
  sonar.properties: sonar.secretKeyPath={{ .Values.sonarqubeFolder }}/secret/sonar-secret.txt
  {{- end }}
  {{- if or .Values.sonarProperties }}
  sonar.properties:
  {{ range $key, $val := .Values.sonarProperties }}
    {{ $key }}={{ $val }}
  {{ end }}
  {{- end }}
    {{- if and .Values.sonarSecretKey .Values.sonarProperties }}
      sonar.secretKeyPath={{ .Values.sonarqubeFolder }}/secret/sonar-secret.txt
    {{- end }}
