---
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "sonarqube.fullname" . }}-search
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- with .Values.searchNodes.podDistributionBudget }}
{{ toYaml . | indent 2 }}
{{- end }}
  selector:
    matchLabels:
      sonarqube.datacenter/type: "search"

---
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "sonarqube.fullname" . }}-app
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- with .Values.ApplicationNodes.podDistributionBudget }}
{{ toYaml . | indent 2 }}
{{- end }}
  selector:
    matchLabels:
      sonarqube.datacenter/type: "app"