{{- if and .Values.prometheusExporter.enabled .Values.prometheusExporter.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "sonarqube.name" . }}
  namespace: {{ .Values.prometheusExporter.podMonitor.namespace | default .Release.Namespace | quote }}
spec:
  jobLabel: {{ .Values.prometheusExporter.podMonitor.jobLabel | quote }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  podMetricsEndpoints:
  - port: monitoring-ce
    path: /
    scheme: http
    {{- if  .Values.prometheusExporter.podMonitor.interval }}
    interval: {{ .Values.prometheusExporter.podMonitor.interval }}
    {{- end }}
    {{- if .Values.prometheusExporter.podMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.prometheusExporter.podMonitor.scrapeTimeout }}
    {{- end }}
  - port: monitoring-web
    path: /
    scheme: http
    {{- if  .Values.prometheusExporter.podMonitor.interval }}
    interval: {{ .Values.prometheusExporter.podMonitor.interval }}
    {{- end }}
    {{- if .Values.prometheusExporter.podMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.prometheusExporter.podMonitor.scrapeTimeout }}
    {{- end }}
  - port: http
    path: /api/monitoring/metrics
    scheme: http
    {{- if  .Values.prometheusExporter.podMonitor.interval }}
    interval: {{ .Values.prometheusExporter.podMonitor.interval }}
    {{- end }}
    {{- if .Values.prometheusExporter.podMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.prometheusExporter.podMonitor.scrapeTimeout }}
    {{- end }}
    bearerTokenSecret:
    {{- if and .Values.monitoringPasscodeSecretName .Values.monitoringPasscodeSecretKey }}
      name: {{ .Values.monitoringPasscodeSecretName }}
      key: {{ .Values.monitoringPasscodeSecretKey }}
    {{- else }}
      name: {{ template "sonarqube.fullname" . }}-monitoring-passcode
      key: SONAR_WEB_SYSTEMPASSCODE
    {{- end }}


  selector:
    matchLabels:
      app: {{ template "sonarqube.name" . }}
{{- end }}