{{- if and .Values.searchNodes.persistence.enabled (not .Values.searchNodes.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "sonarqube.fullname" . }}
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{ if .Values.searchNodes.persistence.annotations}}
  annotations:
    {{- range $key, $value := .Values.searchNodes.persistence.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.searchNodes.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.searchNodes.persistence.size | quote }}
{{- if .Values.searchNodes.persistence.storageClass }}
{{- if (eq "-" .Values.searchNodes.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.searchNodes.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
