{{- $token := .Values.vortexAnalysis.sonarqubeToken }}
{{- $inlineToken := and (not $token.existingSecret) $token.token }}
{{- if and .Values.vortexAnalysis.enabled $inlineToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sonarqube.vortexAnalysis.fullname" . }}
  labels: {{- include "sonarqube.labels" . | nindent 4 }}
    app.kubernetes.io/component: vortex-analysis
type: Opaque
data:
  VORTEX_ANALYSIS_SONARQUBE_TOKEN: {{ $token.token | b64enc | quote }}
{{- end }}
