{{- if and .Values.vortex.enabled .Values.vortex.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sonarqube.vortex.serviceAccountName" . }}
  labels: {{- include "sonarqube.labels" . | nindent 4 }}
    app.kubernetes.io/component: vortex
  {{- with .Values.vortex.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.vortex.serviceAccount.automountToken }}
{{- end }}
