---
# Source: sonarqube-dce/templates/change-admin-password-hook.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: release-name-sonarqube-dce-change-admin-password-hook
  labels:
    app: sonarqube-dce
    heritage: Helm
    release: release-name
    helm.sh/chart: "sonarqube-dce-2025.4.0"
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: release-name-sonarqube-dce-change-admin-password-hook
      labels:
        app: sonarqube-dce
        heritage: Helm
        release: release-name
    spec:
      restartPolicy: OnFailure
      serviceAccountName: default
      containers:
      - name: release-name-sonarqube-dce-change-default-admin-password
        image: sonarqube:2025.3.0-datacenter-app
        securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 0
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
        command: ["sh", "-c", 'until curl -sSi --connect-timeout 100 release-name-sonarqube-dce:9000/api/system/status | grep -w UP; do sleep 10; done; curl -sSi --connect-timeout 100 -u admin:"$CURRENT_ADMIN_PASSWORD" -X POST "release-name-sonarqube-dce:9000/api/users/change_password?login=admin" --data-urlencode "previousPassword=$CURRENT_ADMIN_PASSWORD" --data-urlencode "password=$ADMIN_PASSWORD"']
        env:
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: release-name-sonarqube-dce-admin-password
              key: password
        - name: CURRENT_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: release-name-sonarqube-dce-admin-password
              key: currentPassword
        resources:
          null
