---
# Source: sonarqube-dce/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-sonarqube-dce-app-config
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2025.4.0
    release: release-name
    heritage: Helm
data:
  sonar.properties: |
---
# Source: sonarqube-dce/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-sonarqube-dce-search-config
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2025.4.0
    release: release-name
    heritage: Helm
data:
  sonar.properties: |
