---
# Source: sonarqube-dce/templates/install-plugins.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-sonarqube-dce-install-plugins
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2025.4.0
    release: release-name
    heritage: Helm
data:
  install_plugins.sh: |-
