---
# Source: sonarqube-dce/templates/pod-disruption-budget.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: release-name-sonarqube-dce-search
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2025.4.0
    release: release-name
    heritage: Helm
spec:
  minAvailable: 2

  selector:
    matchLabels:
      sonarqube.datacenter/type: "search"
---
# Source: sonarqube-dce/templates/pod-disruption-budget.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: release-name-sonarqube-dce-app
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2025.4.0
    release: release-name
    heritage: Helm
spec:
  minAvailable: 1

  selector:
    matchLabels:
      sonarqube.datacenter/type: "app"
