---
# Source: sonarqube-dce/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-sonarqube-dce-monitoring-passcode
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2025.4.0
    release: release-name
    heritage: Helm
type: Opaque
data:
  SONAR_WEB_SYSTEMPASSCODE: "ZFowRUIwS3huRisrbnI1KzR2ZlRDYXVuL2VXYnY2Z09vWG9kaUFNcWNGbz0="
---
# Source: sonarqube-dce/templates/secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: release-name-sonarqube-dce-jwt
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2025.4.0
    release: release-name
    heritage: Helm
type: Opaque
data:
  SONAR_AUTH_JWTBASE64HS256SECRET: "ZFowRUIwS3huRisrbnI1KzR2ZlRDYXVuL2VXYnY2Z09vWG9kaUFNcWNGbz0="
---
# Source: sonarqube-dce/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-sonarqube-dce-admin-password
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2025.4.0
    release: release-name
    heritage: Helm
type: Opaque
stringData:
  password: "adminAdmin$1"
  currentPassword: "admin"
---
# Source: sonarqube-dce/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-sonarqube-dce-http-proxies
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2025.4.0
    release: release-name
    heritage: Helm
type: Opaque
stringData:
  PLUGINS-HTTP-PROXY: ""
  PLUGINS-HTTPS-PROXY: ""
  PLUGINS-NO-PROXY: ""
  PROMETHEUS-EXPORTER-HTTP-PROXY: ""
  PROMETHEUS-EXPORTER-HTTPS-PROXY: ""
  PROMETHEUS-EXPORTER-NO-PROXY: ""
