---
# Source: sonarqube-dce/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-sonarqube-dce
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2025.4.0
    release: release-name
    heritage: Helm

spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: sonarqube-dce
    release: release-name
---
# Source: sonarqube-dce/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-sonarqube-dce-headless
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2025.4.0
    release: release-name
    heritage: Helm

spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 9003
      targetPort: hazelcast
      protocol: TCP
      name: hazelcast
  selector:
    app: sonarqube-dce
    release: release-name
---
# Source: sonarqube-dce/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-sonarqube-dce-search
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2025.4.0
    release: release-name
    heritage: Helm

spec:
  type: ClusterIP
  ports:
    - port: 9001
      targetPort: search-port
      protocol: TCP
      name: search
    - port: 9002
      targetPort: es-port
      protocol: TCP
      name: es
  selector:
    app: sonarqube-dce-search
    release: release-name
---
# Source: sonarqube-dce/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-sonarqube-dce-search-headless
  labels:
    app: sonarqube-dce
    chart: sonarqube-dce-2025.4.0
    release: release-name
    heritage: Helm

spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 9001
      targetPort: search-port
      protocol: TCP
      name: search
    - port: 9002
      targetPort: es-port
      protocol: TCP
      name: es
  selector:
    app: sonarqube-dce-search
    release: release-name
