x-google-marketplace:
  clusterConstraints:
    istio:
      type: UNSUPPORTED
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      Releasing SonarQube 10.4.x as a google cloud k8s marketplace application
      Please find the release note here: https://www.sonarsource.com/blog/sonarqube-10-4-release-announcement
  images:
    '':
      properties:
        ApplicationNodes.image.repository:
          type: REPO_WITH_REGISTRY
        ApplicationNodes.image.tag:
          type: TAG
    sonarqube-dce-search:
      properties:
        searchNodes.image.repository:
          type: REPO_WITH_REGISTRY
        searchNodes.image.tag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  appUid:
    type: string
    x-google-marketplace:
      type: APPLICATION_UID
      applicationUid:
        generatedProperties:
          createApplicationBoolean: application.create
  ApplicationNodes.jwtSecret:
    title: JWT Token for app authentication
    description: A HS256 key encoded with base64 (This value must be set before installing the app, see documentation for more details)
    maxLength: 44
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
  postgresql.enabled:
    title: Enable embedded PostgreSQL
    description: If true, PostgreSQL will be installed (not recommended for production use case)
    type: boolean
    default: false
  jdbcOverwrite.enable:
    title: Enable external DB configuration
    description: If true, the JDBC URL, username and password will be used to connect to the database. Make sure enable embedded PostgreSQL is set to false
    type: boolean
    default: true
  jdbcOverwrite.jdbcUrl:
    title: JDBC URL
    description: The JDBC URL to connect to the database
    type: string
    default: ''
  jdbcOverwrite.jdbcUsername:
    title: JDBC Username
    description: The username to connect to the database
    type: string
    default: ''
  jdbcOverwrite.jdbcPassword:
    title: JDBC Password
    description: The password to connect to the database
    type: string
    default: ''
  initSysctl.enabled:
    title: Enable initSysctl privileged initContainer to setup elasticearch kernel parameters.
    description: please read our doc here https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube-dce/README.md#elasticsearch-prerequisites, this should be disabled and setup by your cluster admin
    type: boolean
    default: true
  initFs.enabled:
    title: Enable initFs root initContainer to setup filesystem parameters.
    description: please read our doc here https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube-dce/README.md#production-use-case, this should not be required on google kubernetes clusters
    type: boolean
    default: false
  gcp_marketplace:
    title: GCP Marketplace enabled
    description: this flag indicate to the chart that it runs as a gcp marketplace application
    type: string
    default: 'true'
    enum:
      - 'true'
required:
- name
- namespace
- ApplicationNodes.jwtSecret
