x-google-marketplace:
  clusterConstraints:
    istio:
      type: UNSUPPORTED
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      Releasing SonarQube Server 2025.4.x as a google cloud k8s marketplace application.
      Please find the release notes here: https://www.sonarsource.com/products/sonarqube/whats-new/.
  images:
    '':
      properties:
        ApplicationNodes.image.repository:
          type: REPO_WITH_REGISTRY
        ApplicationNodes.image.tag:
          type: TAG
    sonarqube-dce-search:
      properties:
        searchNodes.image.repository:
          type: REPO_WITH_REGISTRY
        searchNodes.image.tag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  ApplicationNodes.jwtSecret:
    title: Application authentication JWT Token
    description: A HS256 key encoded with base64. Please refer to docs.sonarsource.com for more details.
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
  monitoringPasscode:
    title: Monitoring Passcode
    description: A string encoded with base64 used to verify SonarQube Server's liveness. Please refer to docs.sonarsource.com for more details.
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
  jdbcOverwrite.jdbcUrl:
    title: JDBC URL
    description: The JDBC URL to connect to the database
    type: string
    default: ''
  jdbcOverwrite.jdbcUsername:
    title: JDBC Username
    description: The username to connect to the database
    type: string
    default: ''
  jdbcOverwrite.jdbcPassword:
    title: JDBC Password
    description: The password to connect to the database
    type: string
    default: ''
    x-google-marketplace:
        type: MASKED_FIELD
  ApplicationNodes.replicaCount:
    title: Application nodes replicas
    description: Number of replicas for the Application nodes
    type: integer
    default: 2
  searchNodes.replicaCount:
    title: Search nodes replicas
    description: Number of replicas for the Search nodes
    type: integer
    default: 3
  initSysctl.enabled:
    title: Enable initSysctl privileged initContainer to setup elasticearch kernel parameters.
    description: please read docs.sonarsource.com related to elasticsearch prerequisites, this should be disabled and setup by your cluster admin in most case.
    type: boolean
    default: true
  initFs.enabled:
    title: Enable initFs root initContainer to setup filesystem parameters.
    description: please read docs.sonarsource.com kubernetes section, this should not be required on google kubernetes clusters
    type: boolean
    default: false
  gcp_marketplace:
    title: GCP Marketplace application
    description: This flag is required to indicate that the chart runs as a GCP marketplace application.
    type: string
    default: 'true'
    enum:
      - 'true'
required:
- name
- namespace
- monitoringPasscode
- ApplicationNodes.jwtSecret
- jdbcOverwrite.jdbcUrl
- jdbcOverwrite.jdbcUsername
