on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    
name: Main Workflow
jobs:
  run-static-analysis-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - uses: azure/setup-helm@v3
      with:
        version: latest # default is latest (stable)
        token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
      id: install-helm
    - name: Set up Kubeconform
      uses: bmuschko/setup-kubeconform@v1
    - name: run static compatibility test
      run: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo add bitnami-pre2022 https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
        cd ${{ github.workspace }}/charts/sonarqube
        helm dependency build
        ../../.cirrus/unit_helm_compatibility_test.sh
        cd ${{ github.workspace }}/charts/sonarqube-dce
        helm dependency build
        ../../.cirrus/unit_helm_compatibility_test.sh